### ISSUE TITLE
How to run custom validation against DB?

### ISSUE THREAD

**Issue by ranyefet** [joaquimadraz/compel#13]
Hi @joaquimadraz ,

I was looking for hash validation library and even started building one from scratch. Coming from JS background I was looking for something that validate `Hash`, most of libraries I found only works with `Class`. This library looks great and thanks for that!

One question, as part of my validation I want to be able to validate unique fields in database.
For example I want to validate that param "email" is a valid email address and also is unique in "users" table/collection.

The reason I want it in the same library is because I want to return the validation errors to the client all in the same format of:

```
{
  "errors": {
    "name": [
      "name is required"
    ],
    "email": [
      "email must be valid email address",
      "email must be unique"
    ]
  }
}
```

Is it possible to add custom validation rules?

Thanks,
Ran.

**Comment by joaquimadraz** [comment]
Hey @ranyefet,

Thanks for the feedback, really appreciate it.

You can do custom validations with `#if` method, it receives a `proc` so you can do whatever validation you want, like this:

``` ruby
Compel.any.if(->(input){ input == 1 })
```

For you particular example, I would do something like this:

``` ruby
require 'compel'

def is_unique?(input)
  existing_emails = [
    "person1@email.com",
    "person2@email.com"
  ]

  !existing_emails.include?(input)
  # or User.where(email: input).count == 0 if you are using ActiveRecord
end

email_schema = \
  Compel.string.required
    .email(message: "must be valid email address")
    .if(->(email){ is_unique?(email) }, message: "must be unique")

user_schema = \
  Compel.hash.required
    .keys(name: Compel.string.required, email: email_schema)

result = user_schema.validate({
  name: "Person 3",
  email: "person3@email.com"
})

puts result.valid?
# => true

result = user_schema.validate({
  name: "Person 2",
  email: "person2@email.com"
})

puts result.valid?
# => false

puts result.errors
# => {:email=>["must be unique!"]}
```

Hope this helps!

**Comment by ranyefet** [comment]
@joaquimadraz Thanks for the quick reply, this is exactly what I needed 😄
