### ISSUE TITLE
[enhancement] shortcut request

### ISSUE THREAD

**Issue by goncalvesjoao** [joaquimadraz/compel#7]
@joaquimadraz first of all thanks for building this gem ;)

From the **readme** it seems that the only way to build a "schema" is through the deep method ".keys"
```ruby
schema = Compel.hash.keys({
  first_name: Compel.string.required,
  last_name: Compel.string.required,
  birth_date: Compel.datetime,
  address: Compel.hash.keys({
    line_one: Compel.string.required,
    line_two: Compel.string.default('-'),
    post_code: Compel.string.format(/^\d{4}-\d{3}$/).required,
    country_code: Compel.string.in(['PT', 'GB']).default('PT')
  })
})
```

Because in the future I'll probably forget that to build a schema I'll have to access a ".hash" method that in turn has a ".keys" method, I propose a ".schema" shortcut method that does the same.

This is a bias proposal, in the future I will still remember that ".schema" builds a schema but this might not be true for other people.

Does the following proposal:
```ruby
schema = Compel.schema({
  first_name: Compel.string.required,
  ...
})
```
makes sense to anyone else?

Edit: I'm not suggesting the removal of ".hash.keys", just a alias method that does the same.

**Comment by goncalvesjoao** [comment]
Ok, forget that.
I've just realised that
```ruby
schema = Compel.hash.keys({})
```
is not actually building a schema, not as much as Compel.string is.

In that case, something like this:
```ruby
schema = Compel.hash.keys({
  first_name: Compel.string.required
}).required

Compel.run(object, schema)
```
doesn't happen right?

**Comment by joaquimadraz** [comment]
Thanks for the question!

```ruby
Compel.hash
Compel.string
Compel.integer
```
...returns a schema builders, one for each type.
You can create a `string` schema and validate, it's not required to always be an hash type of schema.
For example:

```ruby
string_schema = Compel.string.format(/^\d{4}-\d{3}$/).required
string_schema.validate('1234')
```

But when you have an `hash` schema, you need to specify what are the keys schemas. and those can be any of the other types.

I don't know if I explained well myself.

**Comment by goncalvesjoao** [comment]
Yeah, you did.

```ruby
schema = Compel.hash.keys({
  first_name: Compel.string.required
}).required

Compel.run(object, schema)
```
Does happen.

I also see no other way of doing that.
